package no.nav.dagpenger.inntekt.v1

enum class PosteringsType(val beskrivelse: String) {
    L_AKSJER_GRUNNFONDSBEVIS_TIL_UNDERKURS("Aksjer/grunnfondsbevis til underkurs"),
    L_ANNET("Annen arbeidsinntekt"),
    L_ANNET_H("Hyre - Annet"),
    L_ANNET_IKKE_SKATTEPLIKTIG("Annen arbeidsinntekt - Ikke skattepliktig"),
    L_ANNET_UTLANDET("Annen arbeidsinntekt - Utlandet"),
    L_ANNET_KONKURS("Annen arbeidsinntekt - Konkurs"),
    L_ANNET_T("Tiltak - Annet"),
    L_ARBEIDSOPPHOLD_KOST("Arbeidsopphold kost"),
    L_ARBEIDSOPPHOLD_LOSJI("Arbeidsopphold losji"),
    L_BEREGNET_SKATT("Beregnet skatt"),
    L_BESØKSREISER_HJEMMET_ANNET("Besøksreiser hjemmet annet"),
    L_BESØKSREISER_HJEMMET_KILOMETERGODTGJØRELSE_BIL("Besøksreiser hjemmet kilometergodtgjørelse bil"),
    L_BETALT_UTENLANDSK_SKATT("Betalt utenlandsk skatt"),
    L_BIL("Bil"),
    L_BOLIG("Bolig"),
    L_BONUS("Bonus"),
    L_BONUS_FRA_FORSVARET("Bonus fra forsvaret"),
    L_BONUS_H("Hyre - Bonus"),
    L_BONUS_T("Tiltak - Bonus"),
    L_ELEKTRONISK_KOMMUNIKASJON("Elektronisk kommunikasjon"),
    L_FAST_BILGODTGJØRELSE("Fast bilgodtgjørelse"),
    L_FAST_TILLEGG("Faste tillegg"),
    L_FAST_TILLEGG_H("Hyre - Faste tillegg"),
    L_FAST_TILLEGG_T("Tiltak - Faste tillegg"),
    L_FASTLØNN("Fastlønn"),
    L_FASTLØNN_H("Hyre - Fastlønn"),
    L_FASTLØNN_T("Tiltak - Fastlønn"),
    L_FERIEPENGER("Feriepenger"),
    L_FERIEPENGER_H("Hyre - Feriepenger"),
    L_FERIEPENGER_T("Tiltak - Feriepenger"),
    L_FOND_FOR_IDRETTSUTØVERE("Fond for idrettsutøvere"),
    L_HELLIGDAGSTILLEGG("Helligdagstillegg"),
    L_HELLIGDAGSTILLEGG_H("Hyre - Helligdagstillegg"),
    L_HELLIGDAGSTILLEGG_T("Tiltak - Helligdagstillegg"),
    L_HONORAR_AKKORD_PROSENT_PROVISJON("Honorar, akkord, prosent eller provisjonslønn"),
    L_HONORAR_AKKORD_PROSENT_PROVISJON_H("Hyre - Honorar, akkord, prosent eller provisjonslønn"),
    L_HYRETILLEGG("Hyretillegg"),
    L_IKKE_SKATTEPLIKTIG_LØNN_FRA_UTENLANDSK_DIPLOM_KONSUL_STASJON(
        "Lønn mv som ikke er skattepliktig i Norge fra utenlandsk diplomatisk eller konsulær stasjon",
    ),
    L_INNBETALING_TIL_UTENLANDSK_PENSJONSORDNING("Innbetaling til utenlandsk pensjonsordning"),
    L_KILOMETERGODTGJØRELSE_BIL("Kilometergodtgjørelse bil"),
    L_KOMMUNAL_OMSORGSLØNN_OG_FOSTERHJEMSGODTGJØRELSE("Kommunal omsorgslønn og fosterhjemsgodtgjørelse"),
    L_KOST_DAGER("Kost (dager)"),
    L_KOST_DØGN("Kost (døgn)"),
    L_KOSTBESPARELSE_I_HJEMMET("Kostbesparelse i hjemmet"),
    L_LØNN_FOR_BARNEPASS_I_BARNETS_HJEM("Lønn og godtgjørelse til dagmamma eller praktikant som passer barn i barnets hjem"),
    L_LØNN_TIL_PRIVATPERSONER_FOR_ARBEID_I_HJEMMET("Lønn og godtgjørelse til privatpersoner for arbeidsoppdrag i oppdragsgivers hjem"),
    L_LØNN_TIL_VERGE_FRA_FYLKESMANNEN("Lønn til verge fra Fylkesmannen"),
    L_LØNN_TIL_VERGE_FRA_STATSFORVALTEREN("Lønn til verge fra Statsforvalteren"),
    L_LØNN_UTBETALT_AV_VELDEDIG_ELLER_ALLMENNYTTIG_INSTITUSJON_ELLER_ORGANISASJON(
        "Lønn og godtgjørelse utbetalt av veldedig eller allmennyttig institusjon eller organisasjon",
    ),
    L_LOSJI("Losji"),
    L_OPSJONER("Opsjoner"),
    L_OVERTIDSGODTGJØRELSE("Overtidsgodtgjørelse"),
    L_OVERTIDSGODTGJØRELSE_H("Hyre - Overtidsgodtgjørelse"),
    L_OVERTIDSGODTGJØRELSE_T("Tiltak - Overtidsgodtgjørelse"),
    L_REISE_ANNET("Reise annet"),
    L_REISE_KOST("Reise kost"),
    L_REISE_LOSJI("Reise losji"),
    L_RENTEFORDEL_LÅN("Rentefordel lån"),
    L_SKATTEPLIKTIG_DEL_FORSIKRINGER("Skattepliktig del av visse typer forsikringer"),
    L_SKATTEPLIKTIG_PERSONALRABATT("Skattepliktig personalrabatt"),
    L_SKATTEPLIKTIG_GODTGJOERELSE_SAERAVTALE_UTLAND("Skattepliktig godtgjørelse særavtale utland"),
    L_SLUTTVEDERLAG(" Sluttvederlag"),
    L_SLUTTVEDERLAG_H("Hyre - Sluttvederlag"),
    L_SLUTTVEDERLAG_T("Tiltak - Sluttvederlag"),
    L_SMUSSTILLEGG("Smusstillegg"),
    L_STIPEND("Stipend"),
    L_STYREHONORAR_OG_GODTGJØRELSE_VERV("Styrehonorar og godtgjørelse i forbindelse med verv"),
    L_TIMELØNN("Timelønn"),
    L_TIMELØNN_H("Hyre - Timelønn"),
    L_TIMELØNN_T("Tiltak - Timelønn"),
    L_TIPS("Tips"),
    L_TREKK_I_LØNN_FOR_FERIE("Trekk i lønn for ferie"),
    L_TREKK_I_LØNN_FOR_FERIE_H("Trekk i lønn for ferie - Hyre"),
    L_TREKK_I_LØNN_FOR_FERIE_T("Trekk i lønn for ferie - Tiltak"),
    L_UREGELMESSIGE_TILLEGG_KNYTTET_TIL_ARBEIDET_TID("Uregelmessige tillegg knyttet til arbeidet tid"),
    L_UREGELMESSIGE_TILLEGG_KNYTTET_TIL_ARBEIDET_TID_H("Hyre - Uregelmessige tillegg knyttet til arbeidet tid"),
    L_UREGELMESSIGE_TILLEGG_KNYTTET_TIL_ARBEIDET_TID_T("Tiltak - Uregelmessige tillegg knyttet til arbeidet tid"),
    L_UREGELMESSIGE_TILLEGG_KNYTTET_TIL_IKKE_ARBEIDET_TID("Uregelmessige tillegg knyttet til ikke-arbeidet tid"),
    L_UREGELMESSIGE_TILLEGG_KNYTTET_TIL_IKKE_ARBEIDET_TID_H("Hyre - Uregelmessige tillegg knyttet til ikke-arbeidet tid"),
    L_UREGELMESSIGE_TILLEGG_KNYTTET_TIL_IKKE_ARBEIDET_TID_T("Tiltak - Uregelmessige tillegg knyttet til ikke-arbeidet tid"),
    L_YRKEBIL_TJENESTLIGBEHOV_KILOMETER("Yrkebil tjenestligbehov kilometer"),
    L_YRKEBIL_TJENESTLIGBEHOV_LISTEPRIS("Yrkebil tjenestligbehov listepris"),
    N_DAGPENGER_TIL_FISKER("Dagpenger til fisker"),
    N_LOTT_KUN_TRYGDEAVGIFT("Lott det skal beregnes trygdeavgift av"),
    N_SYKEPENGER_TIL_FISKER("Sykepenger til fisker"),
    N_VEDERLAG("Vederlag lott"),
    Y_DAGPENGER_TIL_FISKER_SOM_BARE_HAR_HYRE("Dagpenger til fisker som bare har hyre"),
    Y_DAGPENGER_TIL_FISKER_SOM_BARE_HAR_HYRE_FERIETILLEGG("Ferietillegg for dagpenger til fisker som bare har hyre"),
    Y_DAGPENGER_VED_ARBEIDSLØSHET("Dagpenger ved arbeidsløshet"),
    Y_DAGPENGER_VED_ARBEIDSLØSHET_FERIETILLEGG("Ferietillegg for dagpenger ved arbeidsløshet"),
    Y_FORELDREPENGER("Foreldrepenger fra folketrygden"),
    Y_FORELDREPENGER_FERIEPENGER("Feriepenger av foreldrepenger fra folketrygden"),
    Y_SVANGERSKAPSPENGER("Svangerskapspenger"),
    Y_SVANGERSKAPSPENGER_FERIEPENGER("Feriepenger av svangerskapspenger"),
    Y_SYKEPENGER("Sykepenger fra folketrygden"),
    Y_SYKEPENGER_FERIEPENGER("Feriepenger av sykepenger fra folketrygden"),
    Y_SYKEPENGER_TIL_FISKER_SOM_BARE_HAR_HYRE("Sykepenger til fisker som bare har hyre"),
    Y_SYKEPENGER_TIL_FISKER_SOM_BARE_HAR_HYRE_FERIEPENGER("Feriepenger av sykepenger til fisker som bare har hyre"),
    Y_PLEIEPENGER("Pleiepenger fra folketrygden"),
    Y_PLEIEPENGER_FERIEPENGER("Feriepenger av pleiepenger fra folketrygden"),
    Y_OMSORGSPENGER("Omsorgspenger fra folketrygden"),
    Y_OMSORGSPENGER_FERIEPENGER("Feriepenger av omsorgspenger fra folketrygden"),
    Y_OPPLÆRINGSPENGER("Opplæringspenger fra folketrygden"),
    Y_OPPLÆRINGSPENGER_FERIEPENGER("Feriepenger av opplæringspenger fra folketrygden"),
}
