apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "800k"
    config.linkerd.io/proxy-outbound-connect-timeout: 3000ms
spec:
  image: "{{image}}"
  port: 8099
  webproxy: true
  liveness:
    path: /isalive
    initialDelay: 60
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: {{replicas_max}}
  resources:
    limits:
      {{#if resources_cpu_limit}}
      cpu: {{resources_cpu_limit}}
      {{/if}}
      memory: {{resources_memory_limit}}
    requests:
      cpu: {{resources_cpu_request}}
      memory: 512Mi
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      allowAllUsers: true # Dette var default før NAIS endret default til false
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: dp-behandling
        - application: logging
          namespace: nais-system
      external:
        {{#each external_hosts as |host|}}
        - host: "{{host}}"
        {{/each}}
    inbound:
      rules:
        {{#if dev_access}}
        - application: azure-token-generator
          namespace: nais
        {{/if}}
        - application: dp-oppslag-inntekt
        - application: dp-arena-sink
        - application: dp-inntekt-klassifiserer
        - application: dp-inntekt-frontend
        - application: dagpenger-regel-ui
        {{#if dev_access}}
          namespace: teamdagpenger
          cluster: dev-gcp
        {{/if}}
  ingresses:
    - {{ingress}}
  env:
    - name: JDK_JAVA_OPTIONS
      value: -XX:+UseParallelGC -XX:ActiveProcessorCount=4
    - name: CONSUMER_GROUP
      value: "{{consumer_group}}"
    - name: PDL_API_URL
      value: "{{pdl.url}}"
    - name: PDL_API_SCOPE
      value: "{{pdl.scope}}"
    - name: INNTEKTSKOMPONENTEN_API_URL
      value: "{{inntektskomponenten.url}}"
    - name: INNTEKTSKOMPONENTEN_API_SCOPE
      value: "{{inntektskomponenten.scope}}"
  kafka:
    pool: {{kafka_pool}}
  gcp:
    sqlInstances:
      - collation: nb_NO.UTF8
        databases:
          - envVarPrefix: DB
            name: inntekt
        diskAutoresize: true
        diskType: SSD
        highAvailability: {{sql_high_availability}}
        insights:
          enabled: true
          queryStringLength: 4500
          recordApplicationTags: true
          recordClientAddress: true
        maintenance:
          day: 1
          hour: 4
        pointInTimeRecovery: {{sql_point_in_time_recovery}}
        tier: {{sql_tier}}
        type: POSTGRES_15
        {{#if sql_auto_backup_hour}}
        autoBackupHour: {{sql_auto_backup_hour}}
        diskSize: {{sql_disk_size}}
        {{/if}}
        flags:
          - name: "cloudsql.enable_pgaudit"
            value: "on"
          - name: "pgaudit.log"
            value: "write,ddl,role"
          - name: "pgaudit.log_parameter"
            value: "on"
