# Example https://github.com/nais/naiserator/blob/master/examples/nais-max.yaml
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: "{{app}}"
  namespace: "{{namespace}}"
  labels:
    team: "{{team}}"
  annotations:
    config.linkerd.io/proxy-outbound-connect-timeout: 3000ms
spec:
  image: "{{image}}"
  port: 8099
  webproxy: true
  liveness:
    path: /isAlive
    initialDelay: 60
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 6
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 30m
      memory: 512Mi
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
  secureLogs:
    enabled: true
  azure:
    application:
      allowAllUsers: true # Dette var default før NAIS endret default til false
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: "pdl-api.prod-fss-pub.nais.io"
        - host: "team-inntekt-proxy.prod-fss-pub.nais.io"
        - host: "data.brreg.no"
    inbound:
      rules:
        - application: dp-oppslag-inntekt
        - application: dp-arena-sink
        - application: dp-inntekt-klassifiserer
        - application: dagpenger-regel-ui
  kafka:
    pool: nav-prod
  ingresses:
    - https://dp-inntekt-api.intern.nav.no
  env:
    - name: JDK_JAVA_OPTIONS
      value: -XX:+UseParallelGC -XX:ActiveProcessorCount=4
  gcp:
    sqlInstances:
    - autoBackupHour: 1
      collation: nb_NO.UTF8
      databases:
        - envVarPrefix: DB
          name: inntekt
      diskSize: 100
      diskAutoresize: true
      diskType: SSD
      highAvailability: true
      insights:
        enabled: true
        queryStringLength: 4500
        recordApplicationTags: true
        recordClientAddress: true
      maintenance:
        day: 1
        hour: 4
      pointInTimeRecovery: true
      tier:	db-custom-4-15360
      type: POSTGRES_15
      flags:
        - name: cloudsql.enable_pgaudit
          value: "true"
        - name: pgaudit.log
          value: 'write'
