# Example https://github.com/nais/naiserator/blob/master/examples/nais-max.yaml
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{ image }}
  port: 8099
  webproxy: true
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 6
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 300m
      memory: 512Mi
  secureLogs:
    enabled: true
  azure:
    application:
      allowAllUsers: true # Dette var default før NAIS endret default til false
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dp-oppslag-inntekt
        - application: dp-inntekt-klassifiserer
        - application: dp-kronetillegg
          namespace: teamdagpenger
          cluster: prod-gcp
        - application: dagpenger-regel-ui
          namespace: teamdagpenger
          cluster: prod-gcp
  kafka:
    pool: nav-prod
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/{{service_user}}
        mountPath: /var/run/secrets/nais.io/service_user
  ingresses:
    - https://dp-inntekt-api.prod-fss-pub.nais.io
