# Example https://github.com/nais/naiserator/blob/master/examples/nais-max.yaml
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-inntekt-api
spec:
  image: repo.adeo.no:5443/dp-inntekt-api:latest
  port: 8099
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 1000m
      memory: 384Mi
    requests:
      cpu: 100m
      memory: 256Mi
  vault:
    enabled: true
