apiVersion: v1
kind: Service
metadata:
  labels:
    app: dp-inntekt-api-grpc
    team: teamdagpenger
  name: dp-inntekt-api-grpc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8099
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    team: teamdagpenger
    app: dp-inntekt-api
