# Example https://github.com/nais/naiserator/blob/master/examples/nais-max.yaml
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "800k"
spec:
  image: {{ image }}
  port: 8099
  webproxy: true
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  azure:
    application:
      allowAllUsers: true # Dette var default før NAIS endret default til false
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: dp-oppslag-inntekt
        - application: dp-inntekt-klassifiserer
        - application: dp-kronetillegg
          namespace: teamdagpenger
          cluster: dev-gcp
        - application: dagpenger-regel-ui
          namespace: teamdagpenger
          cluster: dev-gcp
  kafka:
    pool: nav-dev
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/dev/{{service_user}}
        mountPath: /var/run/secrets/nais.io/service_user
  secureLogs:
    enabled: true
  ingresses:
    - https://dp-inntekt-api.nais.preprod.local
    - https://dp-inntekt-api.dev-fss-pub.nais.io
