# Example https://github.com/nais/naiserator/blob/master/examples/nais-max.yaml
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: "{{app}}"
  namespace: "{{namespace}}"
  labels:
    team: "{{team}}"
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "800k"
spec:
  image: "{{image}}"
  port: 8099
  webproxy: true
  liveness:
    path: /isAlive
    initialDelay: 60
  readiness:
    path: /isReady
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      allowAllUsers: true # Dette var default før NAIS endret default til false
      enabled: true
  accessPolicy:
    outbound:
      external:
        - host: "pdl-api.dev-fss-pub.nais.io"
        - host: "ikomp-q1.dev-fss-pub.nais.io"
        - host: "ikomp-q2.dev-fss-pub.nais.io"
        - host: "data.brreg.no"
    inbound:
      rules:
        - application: azure-token-generator
          namespace: nais
        - application: dp-oppslag-inntekt
        - application: dp-arena-sink
        - application: dp-inntekt-klassifiserer
        - application: dp-inntekt-frontend
        - application: dagpenger-regel-ui
          namespace: teamdagpenger
          cluster: dev-gcp
  ingresses:
    - https://dp-inntekt-api.intern.dev.nav.no
  env:
    - name: JDK_JAVA_OPTIONS
      value: -XX:+UseParallelGC -XX:ActiveProcessorCount=4
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  gcp:
    sqlInstances:
      - collation: nb_NO.UTF8
        databases:
          - envVarPrefix: DB
            name: inntekt
        diskAutoresize: true
        diskType: SSD
        highAvailability: false
        insights:
          enabled: true
          queryStringLength: 4500
          recordApplicationTags: true
          recordClientAddress: true
        maintenance:
          day: 1
          hour: 4
        pointInTimeRecovery: false
        tier: db-custom-1-3840
        type: POSTGRES_15
        flags:
          - name: "cloudsql.enable_pgaudit"
            value: "on"
          - name: "pgaudit.log"
            value: "write,ddl,role"
          - name: "pgaudit.log_parameter"
            value: "on"
