name: Build and publish gRPC client

on:
  push:
    paths:
      - 'dp-inntekt-grpc/**'
      - '.github/workflows/dp-inntekt-grpc-build.yml'
      - jitpack.yml

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17.x'

      - name: Cache gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('dp-inntekt-grpc/build.gradle.kts') }}-${{ hashFiles('buildSrc/src/main/kotlin/Constants.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew :dp-inntekt-grpc:build

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
        contents: write
        packages: write
    if: github.ref == 'refs/heads/master' && !contains(github.event.head_commit.message, 'ci skip')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set release tag
        run: |
          export TAG_NAME="$(TZ="Europe/Oslo" date +%Y.%m.%d-%H.%M).$(echo $GITHUB_SHA | cut -c 1-12)"
          echo "RELEASE_TAG=$TAG_NAME" >> $GITHUB_ENV

      - name: Set changelog
        # (Escape newlines see https://github.com/actions/create-release/issues/25)
        run: |
          text="$(git --no-pager log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%h %s")"
          text="${text//$'%'/%25}"
          text="${text//$'\n'/%0A}"
          text="${text//$'\r'/%0D}"
          echo "CHANGELOG=$text" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: ${{ env.RELEASE_TAG }}
          body: |
            Changes in this Release
            ${{ env.CHANGELOG }}
          draft: false
          prerelease: false