name: Publish dp-inntekt-kontrakter

on:
  push:
    paths:
      - 'dp-inntekt-kontrakter/**'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Java and build
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/wrapper-validation-action@v2.1.1
      - uses: gradle/gradle-build-action@v3.3.1
        env:
          # Eksluder test dependencies
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: compileClasspath|runtimeClasspath
        with:
          gradle-version: wrapper
          dependency-graph: generate-and-submit
          arguments: --configuration-cache :dp-inntekt-kontrakter:test


  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'ci skip')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set release tag
        run: |
          export TAG_NAME="1_$(TZ="Europe/Oslo" date +%Y%m%d).$(echo $GITHUB_SHA | cut -c 1-6)"
          echo "RELEASE_TAG=$TAG_NAME" >> $GITHUB_ENV
      - uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5 # ratchet:ncipollo/release-action@v1
        with:
          tag: ${{ env.RELEASE_TAG }}
          generateReleaseNotes: true
    outputs:
      tag: ${{ env.RELEASE_TAG }}
  publish:
    runs-on: ubuntu-latest
    needs: release
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17.x
          cache: 'gradle'
      - name: publish
        run: ./gradlew -Pversion="$(echo ${{ needs.release.outputs.tag }})" :dp-inntekt-kontrakter:publish
        env:
          ORG_GRADLE_PROJECT_githubUser: x-access-token
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}